[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "DOGCosmoS"
dynamic = ["version"]
authors = [
    { name="Katharina Kain", email="a1057247@univie.ac.at" },
]
description = "A package to analyse the dynamics of galaxies in cosmological simulations."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy >=1.23",
]

[project.urls]
Homepage = "https://github.com/katharinaka/DOGcosmoS.git"

[tool.setuptools.dynamic]
version = {attr = "DOGCosmoS.__version__"}
